[2024-05-17T15:20:29.860+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T15:20:29.878+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api manual__2024-05-17T15:20:13.892189+00:00 [queued]>
[2024-05-17T15:20:29.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api manual__2024-05-17T15:20:13.892189+00:00 [queued]>
[2024-05-17T15:20:29.891+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-05-17T15:20:29.909+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2024-05-17 15:20:13.892189+00:00
[2024-05-17T15:20:29.918+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=422) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T15:20:29.920+0000] {standard_task_runner.py:63} INFO - Started process 424 to run task
[2024-05-17T15:20:29.920+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'manual__2024-05-17T15:20:13.892189+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmpmhr076sm']
[2024-05-17T15:20:29.924+0000] {standard_task_runner.py:91} INFO - Job 190: Subtask extract_data_from_api
[2024-05-17T15:20:29.968+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api manual__2024-05-17T15:20:13.892189+00:00 [running]> on host 6239d20906ca
[2024-05-17T15:20:30.042+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ostapenko.vctr@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T15:20:13.892189+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T15:20:13.892189+00:00'
[2024-05-17T15:20:30.062+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T15:20:30.074+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T15:20:30.082+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process_sales.py", line 10, in run_job1
    "date": {{ ds }},
               ^^
NameError: name 'ds' is not defined
[2024-05-17T15:20:30.105+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=process_sales, task_id=extract_data_from_api, run_id=manual__2024-05-17T15:20:13.892189+00:00, execution_date=20240517T152013, start_date=20240517T152029, end_date=20240517T152030
[2024-05-17T15:20:30.117+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 190 for task extract_data_from_api (name 'ds' is not defined; 424)
[2024-05-17T15:20:30.135+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-17T15:20:30.157+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-17T15:20:30.162+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
