[2024-05-17T15:25:19.456+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T15:25:19.481+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api manual__2024-05-17T15:25:17.370323+00:00 [queued]>
[2024-05-17T15:25:19.490+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api manual__2024-05-17T15:25:17.370323+00:00 [queued]>
[2024-05-17T15:25:19.491+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-17T15:25:19.504+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2024-05-17 15:25:17.370323+00:00
[2024-05-17T15:25:19.510+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=498) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T15:25:19.511+0000] {standard_task_runner.py:63} INFO - Started process 500 to run task
[2024-05-17T15:25:19.511+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'manual__2024-05-17T15:25:17.370323+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmpfvot20ce']
[2024-05-17T15:25:19.513+0000] {standard_task_runner.py:91} INFO - Job 194: Subtask extract_data_from_api
[2024-05-17T15:25:19.556+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api manual__2024-05-17T15:25:17.370323+00:00 [running]> on host 6239d20906ca
[2024-05-17T15:25:19.628+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ostapenko.vctr@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T15:25:17.370323+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T15:25:17.370323+00:00'
[2024-05-17T15:25:19.629+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T15:25:19.630+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T15:25:19.631+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: run_job1() takes 1 positional argument but 10 were given
[2024-05-17T15:25:19.638+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=process_sales, task_id=extract_data_from_api, run_id=manual__2024-05-17T15:25:17.370323+00:00, execution_date=20240517T152517, start_date=20240517T152519, end_date=20240517T152519
[2024-05-17T15:25:19.648+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 194 for task extract_data_from_api (run_job1() takes 1 positional argument but 10 were given; 500)
[2024-05-17T15:25:19.685+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-17T15:25:19.706+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-17T15:25:19.708+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
