[2024-05-17T15:28:48.396+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T15:28:48.417+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.convert_to_avro manual__2024-05-17T15:28:34.216436+00:00 [queued]>
[2024-05-17T15:28:48.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.convert_to_avro manual__2024-05-17T15:28:34.216436+00:00 [queued]>
[2024-05-17T15:28:48.425+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-05-17T15:28:48.437+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): convert_to_avro> on 2024-05-17 15:28:34.216436+00:00
[2024-05-17T15:28:48.443+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=562) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T15:28:48.445+0000] {standard_task_runner.py:63} INFO - Started process 564 to run task
[2024-05-17T15:28:48.444+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'convert_to_avro', 'manual__2024-05-17T15:28:34.216436+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmp5ppe1mey']
[2024-05-17T15:28:48.446+0000] {standard_task_runner.py:91} INFO - Job 199: Subtask convert_to_avro
[2024-05-17T15:28:48.479+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.convert_to_avro manual__2024-05-17T15:28:34.216436+00:00 [running]> on host 6239d20906ca
[2024-05-17T15:28:48.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ostapenko.vctr@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='convert_to_avro' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T15:28:34.216436+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T15:28:34.216436+00:00'
[2024-05-17T15:28:48.558+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T15:28:48.560+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T15:28:48.562+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: run_job2() takes 0 positional arguments but 1 was given
[2024-05-17T15:28:48.572+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=process_sales, task_id=convert_to_avro, run_id=manual__2024-05-17T15:28:34.216436+00:00, execution_date=20240517T152834, start_date=20240517T152848, end_date=20240517T152848
[2024-05-17T15:28:48.599+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 199 for task convert_to_avro (run_job2() takes 0 positional arguments but 1 was given; 564)
[2024-05-17T15:28:48.660+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-17T15:28:48.687+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-17T15:28:48.690+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
